services:
  routehubservice:
    image: routehubservice
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - cache-database
    network_mode: "host"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: "host"
    
  cache-database:
    image: redis
    network_mode: "host"