// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	entdomain "RouteHub.Service.Dashboard/ent/domain"
	"RouteHub.Service.Dashboard/ent/organization"
	"RouteHub.Service.Dashboard/ent/predicate"
	"RouteHub.Service.Dashboard/ent/schema/enums/domain"
	"RouteHub.Service.Dashboard/ent/schema/mixin"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DomainUpdate is the builder for updating Domain entities.
type DomainUpdate struct {
	config
	hooks    []Hook
	mutation *DomainMutation
}

// Where appends a list predicates to the DomainUpdate builder.
func (du *DomainUpdate) Where(ps ...predicate.Domain) *DomainUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DomainUpdate) SetName(s string) *DomainUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DomainUpdate) SetNillableName(s *string) *DomainUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// SetURL sets the "url" field.
func (du *DomainUpdate) SetURL(s string) *DomainUpdate {
	du.mutation.SetURL(s)
	return du
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (du *DomainUpdate) SetNillableURL(s *string) *DomainUpdate {
	if s != nil {
		du.SetURL(*s)
	}
	return du
}

// SetStatus sets the "status" field.
func (du *DomainUpdate) SetStatus(ds domain.DomainState) *DomainUpdate {
	du.mutation.SetStatus(ds)
	return du
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (du *DomainUpdate) SetNillableStatus(ds *domain.DomainState) *DomainUpdate {
	if ds != nil {
		du.SetStatus(*ds)
	}
	return du
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (du *DomainUpdate) SetOrganizationID(id mixin.ID) *DomainUpdate {
	du.mutation.SetOrganizationID(id)
	return du
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (du *DomainUpdate) SetOrganization(o *Organization) *DomainUpdate {
	return du.SetOrganizationID(o.ID)
}

// Mutation returns the DomainMutation object of the builder.
func (du *DomainUpdate) Mutation() *DomainMutation {
	return du.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (du *DomainUpdate) ClearOrganization() *DomainUpdate {
	du.mutation.ClearOrganization()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DomainUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DomainUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DomainUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DomainUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DomainUpdate) check() error {
	if v, ok := du.mutation.Name(); ok {
		if err := entdomain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Domain.name": %w`, err)}
		}
	}
	if v, ok := du.mutation.URL(); ok {
		if err := entdomain.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Domain.url": %w`, err)}
		}
	}
	if v, ok := du.mutation.Status(); ok {
		if err := entdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Domain.status": %w`, err)}
		}
	}
	if du.mutation.OrganizationCleared() && len(du.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Domain.organization"`)
	}
	return nil
}

func (du *DomainUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(entdomain.Table, entdomain.Columns, sqlgraph.NewFieldSpec(entdomain.FieldID, field.TypeString))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(entdomain.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.URL(); ok {
		_spec.SetField(entdomain.FieldURL, field.TypeString, value)
	}
	if value, ok := du.mutation.Status(); ok {
		_spec.SetField(entdomain.FieldStatus, field.TypeEnum, value)
	}
	if du.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entdomain.OrganizationTable,
			Columns: []string{entdomain.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entdomain.OrganizationTable,
			Columns: []string{entdomain.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DomainUpdateOne is the builder for updating a single Domain entity.
type DomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DomainMutation
}

// SetName sets the "name" field.
func (duo *DomainUpdateOne) SetName(s string) *DomainUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableName(s *string) *DomainUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// SetURL sets the "url" field.
func (duo *DomainUpdateOne) SetURL(s string) *DomainUpdateOne {
	duo.mutation.SetURL(s)
	return duo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableURL(s *string) *DomainUpdateOne {
	if s != nil {
		duo.SetURL(*s)
	}
	return duo
}

// SetStatus sets the "status" field.
func (duo *DomainUpdateOne) SetStatus(ds domain.DomainState) *DomainUpdateOne {
	duo.mutation.SetStatus(ds)
	return duo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (duo *DomainUpdateOne) SetNillableStatus(ds *domain.DomainState) *DomainUpdateOne {
	if ds != nil {
		duo.SetStatus(*ds)
	}
	return duo
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (duo *DomainUpdateOne) SetOrganizationID(id mixin.ID) *DomainUpdateOne {
	duo.mutation.SetOrganizationID(id)
	return duo
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (duo *DomainUpdateOne) SetOrganization(o *Organization) *DomainUpdateOne {
	return duo.SetOrganizationID(o.ID)
}

// Mutation returns the DomainMutation object of the builder.
func (duo *DomainUpdateOne) Mutation() *DomainMutation {
	return duo.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (duo *DomainUpdateOne) ClearOrganization() *DomainUpdateOne {
	duo.mutation.ClearOrganization()
	return duo
}

// Where appends a list predicates to the DomainUpdate builder.
func (duo *DomainUpdateOne) Where(ps ...predicate.Domain) *DomainUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DomainUpdateOne) Select(field string, fields ...string) *DomainUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Domain entity.
func (duo *DomainUpdateOne) Save(ctx context.Context) (*Domain, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DomainUpdateOne) SaveX(ctx context.Context) *Domain {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DomainUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DomainUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DomainUpdateOne) check() error {
	if v, ok := duo.mutation.Name(); ok {
		if err := entdomain.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Domain.name": %w`, err)}
		}
	}
	if v, ok := duo.mutation.URL(); ok {
		if err := entdomain.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Domain.url": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Status(); ok {
		if err := entdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Domain.status": %w`, err)}
		}
	}
	if duo.mutation.OrganizationCleared() && len(duo.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Domain.organization"`)
	}
	return nil
}

func (duo *DomainUpdateOne) sqlSave(ctx context.Context) (_node *Domain, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entdomain.Table, entdomain.Columns, sqlgraph.NewFieldSpec(entdomain.FieldID, field.TypeString))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Domain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entdomain.FieldID)
		for _, f := range fields {
			if !entdomain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entdomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(entdomain.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.URL(); ok {
		_spec.SetField(entdomain.FieldURL, field.TypeString, value)
	}
	if value, ok := duo.mutation.Status(); ok {
		_spec.SetField(entdomain.FieldStatus, field.TypeEnum, value)
	}
	if duo.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entdomain.OrganizationTable,
			Columns: []string{entdomain.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entdomain.OrganizationTable,
			Columns: []string{entdomain.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Domain{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
