// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"RouteHub.Service.Dashboard/ent/hub"
	"RouteHub.Service.Dashboard/ent/page"
	"RouteHub.Service.Dashboard/ent/schema/enums"
	"RouteHub.Service.Dashboard/ent/schema/mixin"
	"RouteHub.Service.Dashboard/ent/schema/types"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PageCreate is the builder for creating a Page entity.
type PageCreate struct {
	config
	mutation *PageMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PageCreate) SetName(s string) *PageCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetSlug sets the "slug" field.
func (pc *PageCreate) SetSlug(s string) *PageCreate {
	pc.mutation.SetSlug(s)
	return pc
}

// SetPageDescription sets the "page_description" field.
func (pc *PageCreate) SetPageDescription(s string) *PageCreate {
	pc.mutation.SetPageDescription(s)
	return pc
}

// SetNillablePageDescription sets the "page_description" field if the given value is not nil.
func (pc *PageCreate) SetNillablePageDescription(s *string) *PageCreate {
	if s != nil {
		pc.SetPageDescription(*s)
	}
	return pc
}

// SetPageContentJSON sets the "page_content_json" field.
func (pc *PageCreate) SetPageContentJSON(s string) *PageCreate {
	pc.mutation.SetPageContentJSON(s)
	return pc
}

// SetNillablePageContentJSON sets the "page_content_json" field if the given value is not nil.
func (pc *PageCreate) SetNillablePageContentJSON(s *string) *PageCreate {
	if s != nil {
		pc.SetPageContentJSON(*s)
	}
	return pc
}

// SetPageContentHTML sets the "page_content_html" field.
func (pc *PageCreate) SetPageContentHTML(s string) *PageCreate {
	pc.mutation.SetPageContentHTML(s)
	return pc
}

// SetNillablePageContentHTML sets the "page_content_html" field if the given value is not nil.
func (pc *PageCreate) SetNillablePageContentHTML(s *string) *PageCreate {
	if s != nil {
		pc.SetPageContentHTML(*s)
	}
	return pc
}

// SetStatus sets the "status" field.
func (pc *PageCreate) SetStatus(es enums.StatusState) *PageCreate {
	pc.mutation.SetStatus(es)
	return pc
}

// SetMetaDescription sets the "meta_description" field.
func (pc *PageCreate) SetMetaDescription(td *types.MetaDescription) *PageCreate {
	pc.mutation.SetMetaDescription(td)
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PageCreate) SetCreatedAt(t time.Time) *PageCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PageCreate) SetNillableCreatedAt(t *time.Time) *PageCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PageCreate) SetID(m mixin.ID) *PageCreate {
	pc.mutation.SetID(m)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PageCreate) SetNillableID(m *mixin.ID) *PageCreate {
	if m != nil {
		pc.SetID(*m)
	}
	return pc
}

// SetHubID sets the "hub" edge to the Hub entity by ID.
func (pc *PageCreate) SetHubID(id mixin.ID) *PageCreate {
	pc.mutation.SetHubID(id)
	return pc
}

// SetHub sets the "hub" edge to the Hub entity.
func (pc *PageCreate) SetHub(h *Hub) *PageCreate {
	return pc.SetHubID(h.ID)
}

// Mutation returns the PageMutation object of the builder.
func (pc *PageCreate) Mutation() *PageMutation {
	return pc.mutation
}

// Save creates the Page in the database.
func (pc *PageCreate) Save(ctx context.Context) (*Page, error) {
	if err := pc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PageCreate) SaveX(ctx context.Context) *Page {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PageCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PageCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PageCreate) defaults() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		if page.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized page.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := page.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		if page.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized page.DefaultID (forgotten import ent/runtime?)")
		}
		v := page.DefaultID()
		pc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pc *PageCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Page.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := page.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Page.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Page.slug"`)}
	}
	if v, ok := pc.mutation.Slug(); ok {
		if err := page.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Page.slug": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Page.status"`)}
	}
	if v, ok := pc.mutation.Status(); ok {
		if err := page.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Page.status": %w`, err)}
		}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Page.created_at"`)}
	}
	if len(pc.mutation.HubIDs()) == 0 {
		return &ValidationError{Name: "hub", err: errors.New(`ent: missing required edge "Page.hub"`)}
	}
	return nil
}

func (pc *PageCreate) sqlSave(ctx context.Context) (*Page, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(mixin.ID); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Page.ID type: %T", _spec.ID.Value)
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PageCreate) createSpec() (*Page, *sqlgraph.CreateSpec) {
	var (
		_node = &Page{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(page.Table, sqlgraph.NewFieldSpec(page.FieldID, field.TypeString))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(page.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Slug(); ok {
		_spec.SetField(page.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := pc.mutation.PageDescription(); ok {
		_spec.SetField(page.FieldPageDescription, field.TypeString, value)
		_node.PageDescription = value
	}
	if value, ok := pc.mutation.PageContentJSON(); ok {
		_spec.SetField(page.FieldPageContentJSON, field.TypeString, value)
		_node.PageContentJSON = value
	}
	if value, ok := pc.mutation.PageContentHTML(); ok {
		_spec.SetField(page.FieldPageContentHTML, field.TypeString, value)
		_node.PageContentHTML = value
	}
	if value, ok := pc.mutation.Status(); ok {
		_spec.SetField(page.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := pc.mutation.MetaDescription(); ok {
		_spec.SetField(page.FieldMetaDescription, field.TypeJSON, value)
		_node.MetaDescription = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(page.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := pc.mutation.HubIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.HubTable,
			Columns: []string{page.HubColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hub.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.hub_fk = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PageCreateBulk is the builder for creating many Page entities in bulk.
type PageCreateBulk struct {
	config
	err      error
	builders []*PageCreate
}

// Save creates the Page entities in the database.
func (pcb *PageCreateBulk) Save(ctx context.Context) ([]*Page, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Page, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PageCreateBulk) SaveX(ctx context.Context) []*Page {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PageCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PageCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
