// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Domain is the predicate function for entdomain builders.
type Domain func(*sql.Selector)

// Hub is the predicate function for hub builders.
type Hub func(*sql.Selector)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)
